# Generated by Django 5.1.1 on 2024-09-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_clothingentry_alter_moodentry_mood_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
